[package]
name = "pdc"
version = "0.2.0"
description = "Pulpcore Dependency Checker"
repository = "https://github.com/fao89/pdc"
authors = ["Fabricio Aguiar <fabricio.aguiar@gmail.com>"]
readme = "README.md"
license = "GPL-2.0+"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
reqwest = { version = "0.10.4", features = ["json"] }
semver = "0.9.0"
serde_json = "1.0.53"
tokio = { version = "0.2", features = ["macros"] }
